### ISSUE TITLE
New templates for the bibliography.

### ISSUE THREAD

**Issue by joaopalmeiro** [joaomlourenco/novathesis#101] opened 2020-01-13 11:31 UTC
Based on this [document](http://web.mit.edu/rsi/www/pdfs/bibtex-format.pdf) and the need to cite technical reports and websites (and perhaps GitHub repositories, for example), I think it would be interesting to complement the available bibliography with new templates for these two cases at least. 

I can help with this if it is possible.

**Comment by joaomlourenco** [comment] 2020-01-13 14:04
João, that you for the offering of help.  Any help is always welcome.
But I'm not sure I understood the question here. Or, if I did, the problem is not a problem anymore. The NOVAthesis template uses BibLaTEX (with bibtex as the backend) to process bibliography. And if you take a look at the manual (https://ftp.eq.uc.pt/software/TeX/macros/latex/contrib/biblatex/doc/biblatex.pdf), section "2.1 Entry Types" (page 8) you'll find many different types ob bibliography entries, including the ones you cited.
I'll close this issue, please reopen if I'm wrong. Thanks.

**Closed by joaomlourenco** 2020-01-13 14:04 UTC
Labels: invalid

**Comment by joaopalmeiro** [comment] 2020-01-13 14:16
I apologize if I was not clear with my idea.  My idea is just to complement this file (https://github.com/joaomlourenco/novathesis/blob/master/bibliography.bib) with other examples (a.k.a. templates), such as references to websites and technical reports so that anyone who will start working with this template will have more examples of how to reference each type of reference without having to check online or the documentation (ignoring here very specific cases where documentation will be critical).

Does that make sense to you, Professor?

Btw, thanks for the document! :D

**Comment by joaopalmeiro** [comment] 2020-01-13 14:30
Also, should I rename this issue to "New examples for the bibliography."?
